### ISSUE TITLE
ConstraintLayout Performance varying with different Android versions

### ISSUE THREAD

**Issue by kaushiknsanji** [kaushiknsanji/Books_Library_App#4]
The `ConstraintLayout` used in the items shown by the `RecyclerView` of the `ViewPager` is showing a variance in the performance of Measure-Layout-Draw. We can observe that the `RecyclerView` is pretty janky when the app is used on Android 5 OS. It appears very smooth when the app is used on Android 7 OS.

### Performance in Android 7

![android7_perf](https://user-images.githubusercontent.com/26028981/32454448-46b00594-c345-11e7-9e14-35a2013a2471.gif)

As seen in the above GIF, there is a smooth flow in the scrolling and also when transitioning to the other tab in the ViewPager. Below are the details of Measure-Layout-Draw performance retrieved through the Android Monitor.

_Layout performance of the complete view_
<img src="https://user-images.githubusercontent.com/26028981/32414083-44591b1a-c245-11e7-8465-ec6a31229679.png" width="40%" /> 

_Grid View Performance_
<img src="https://user-images.githubusercontent.com/26028981/32414084-461294c2-c245-11e7-99ae-3d69868a35f1.png" width="40%" />

_List View Performance_
<img src="https://user-images.githubusercontent.com/26028981/32414085-4770ac64-c245-11e7-8fb9-dccab3bd78bc.png" width="40%" />

_ViewPager Performance_
<img src="https://user-images.githubusercontent.com/26028981/32414087-48703a08-c245-11e7-8bb8-926fcf53cf2d.png" width="40%" />

### Performance in Android 5

![android5_perf](https://user-images.githubusercontent.com/26028981/32454454-4b5f5d60-c345-11e7-8526-e3af10c93ee4.gif)

As seen in the above GIF, when user scrolls some frames are lost or it starts to jank. Below are the details of Measure-Layout-Draw performance retrieved through the Android Monitor.

_Layout performance of the complete view_
<img src="https://user-images.githubusercontent.com/26028981/32454396-23058cc2-c345-11e7-8847-66d9ac38a41e.png" width="40%" />

_Grid View Performance_
<img src="https://user-images.githubusercontent.com/26028981/32454409-2792e366-c345-11e7-81c2-74b4a55614fd.png" width="40%" />

_List View Performance_
<img src="https://user-images.githubusercontent.com/26028981/32454417-2d6ac128-c345-11e7-9a8e-4e0c061bc1b9.png" width="40%" />

_ViewPager Performance_
<img src="https://user-images.githubusercontent.com/26028981/32454425-3547acd0-c345-11e7-9705-fc0cd88d84c4.png" width="40%" />

From the above performance evaluation, it can be observed that the Draw time in Android 5 is double the Draw time taken in Android 7.

When testing this (in Android 5), the below Info log line from Android system appears during scrolling at times -
```
10-26 20:48:35.899 5512-5512/com.example.kaushiknsanji.bookslibrary I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
```

These are the test results obtained through Android Emulation of Nexus 5X with Android 7 and Android 5. Emulation was accelerated with Hardware acceleration. The janky problem was also observed on a device (Sony Xperia Z1) runnning on Android 5.1.1.

_Couple of things I would like to know on this_ - 
1. Why there is a difference in ConstraintLayout Performance on different Android versions?
2. How to fix this issue for Android versions having the said problem?

**Comment by java2men** [comment]
I have this problem on my current project. I tried constraint-layout: 1.1.0-beta6 with the optimizations app: layout_optimizationLevel = "direct | barrier | chains". It did not help.
Did you find a solution to the problem?

**Comment by anubhavmalik** [comment]
I am trying to improve the performance of my recycler view too. Am using diff utils, databinding, never use notifyDatasetChanged()... But I cannot help if constraint layout draw performance is poor with these optimisations.

I am deparately looking for better solutions.

**Comment by kaushiknsanji** [comment]
Thank you all for the help and support. RecyclerView and Constraint Layout have improved a lot since the time this issue was created. Hence closing this issue for now.
